Use location relative to script directory instead of home directory
hackclub/spade pull request #25
Opened 2023-11-21 14:39 UTC by khrj

This makes `pc/jerry/refresh.sh` use directories relative to the script directory instead of the home directory.
This change is backwards compatible with the
```
~/spade
~/jerryscript_build
```
setup.

2023-11-21 14:39 UTC, khrj commented
(@grymmy)

2023-11-21 15:19 UTC, grymmy requested changes

2023-11-21 15:19 UTC, grymmy commented on src/pc/jerry/refresh.sh
> +
Can we please add ooooone more little change and ensure that the jerryscript build directory exists, and if it doesn't, state a clear human-readable warning saying that you should clone it etc?

One issue I observe is that the spade directions specifically tell you to check out the jerryscript_build repo into your home directory, but you may have checked out Spade somewhere else (for instance, I put stuff in ~/Work).  This causes this script to fail.

2024-03-01 16:22 UTC, grymmy commented
closing this as the dockerized builds are now used and supercede this

2024-03-01 16:22 UTC, closed without merging